# Generated by Django 3.2.6 on 2021-09-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accountability',
            new_name='Invoice',
        ),
    ]
